# Generated by Django 4.2.11 on 2024-03-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("employer", "Employer"), ("job_seeker", "Job Seeker")],
                default="employer",
                max_length=20,
            ),
        ),
    ]
